example/package.json
package.json
src/cli/dev.ts
tsconfig.json
types/ts-node-dev/index.d.ts
yarn.lock

feat: power dev command with ts-node-dev

---

config.d.ts
config.js
package.json
src/cli/commands/build.ts
src/cli/commands/create/app.tsx
src/cli/commands/db/init.ts
src/cli/commands/db/migrate/apply.ts
src/cli/commands/db/migrate/plan.ts
src/cli/commands/db/migrate/rollback.ts
src/cli/commands/db/ui.ts
src/cli/commands/dev.tsx
src/cli/commands/generate.ts
src/framework/plugin.ts
src/framework/start.ts
src/utils/db-driver.ts
src/utils/deploy-target.ts

feat: remove config file

---

package.json
src/cli/commands/create/app.tsx
src/utils/package-manager.ts
src/utils/process.ts

feat: better scaffolded world & prettier system

---

README.md

docs: embed video

---

src/framework/app.ts
src/lib/logger/index.spec.ts
src/lib/logger/index.ts

feat: context logger

---

src/cli/index.ts

fix: command rendering glitch

---

docs/index.html

Just added [`auto2top`](https://docsify.now.sh/configuration?id=auto2top) in order to scroll to top when changing the current route.

docs: scroll to top on docs page change

---

src/watcher/chokidar.ts
src/watcher/runner.ts
src/watcher/watcher.ts

- Makes sure runner isn't restarted before it finishes to run properly
- #74

fix: EPIPE error when server is restarted several times

---

src/cli/helpers/CLI.ts
src/cli/helpers/helpers.ts

- Prevent positional flags
- Make `santa <namespace> <namespace> --help` working

fix: cli command parsing

---

src/framework/app.ts

improve: show url in server start msg

---

src/core/plugin/index.ts
src/framework/app.ts

feat: allow plugins to register backing types

---

src/lib/logger/__snapshots__/index.spec.ts.snap
src/lib/logger/index.spec.ts
src/lib/logger/pino.ts
src/lib/logger/root-logger.ts
src/lib/utils/index.ts

had some time... polishing/relaxing :D 
closes #328

feat(logger): pretty mode color control

---

src/framework/app.ts
src/framework/layout.ts
src/framework/nexus.ts

feat: warn+exit on missing schema+app modules

---

docs/references/api.md
src/core/plugin/index.ts
src/framework/app.ts
src/framework/layout.ts
src/framework/schema/index.ts
src/framework/schema/logger.ts
src/framework/schema/modules.ts
src/framework/schema/nexus.ts
src/framework/schema/schema.ts
src/framework/start.ts
src/lib/utils/index.ts
test/__helpers/run.ts

- relay connections are a first class concept in core now
- new schema settings api
- relay connections are available out of the box
This is experimental. We will need to get feedback and reflect, possibly a lot, before 1.0.
closes #117

feat(schema): relay connections

---

package.json
src/lib/logger/__snapshots__/index.spec.ts.snap
src/lib/logger/demo.ts
src/lib/logger/index.spec.ts
src/lib/logger/prettifier.ts
src/lib/utils/index.ts

feat(logger): format multiline context

---

src/lib/logger/__snapshots__/index.spec.ts.snap
src/lib/logger/index.spec.ts
src/lib/logger/pino.ts
src/lib/logger/prettifier.ts
src/lib/logger/root-logger.ts
src/lib/utils/index.ts

feat(logger): pretty mode time diffs

---

docs/getting-started/tutorial.md
docs/references/conventions.md
docs/references/recipes.md
src/cli/commands/create/app.ts
src/cli/commands/doctor.ts
src/framework/app.ts
src/framework/layout/index.ts
src/framework/layout/layout.ts
src/framework/layout/schema-modules.ts
src/framework/schema/index.ts
src/framework/start.ts
test/integration/build.spec.ts
test/integration/prisma/build.spec.ts

feat(layout): graphql instead of schema

---

src/framework/schema/nexus.ts
src/framework/schema/schema.ts

closes https://github.com/graphql-nexus/nexus-future/issues/122#issuecomment-583746151

feat: expose schema arg func on schema api

---

src/framework/server.ts

This allows to render colorless error messages in the GraphQL IDE's, but keep colorful messages in the terminal logs _WHEN_ app is in dev mode.
It now also uses the logger to provide structured logs when in prod

feat: add custom graphql error formatter

---

.github/workflows/ci-cd.yml
README.md
package.json
src/cli/commands/__default.ts
src/cli/commands/create/app.ts
src/utils/e2e-testing.ts
yarn.lock

- enable trace logging during e2e test
- make create app command own env var overrides
closes #428

tests: make e2e be not interactive

---

.github/workflows/pr-ci.yml
.github/workflows/trunk-cd.yml
README.md
package.json
src/cli/commands/create/app.ts
src/lib/own-package/index.ts
src/utils/artifact-generation.ts
src/utils/e2e-testing.ts
test/system/__snapshots__/cli-entrypoint-create-app.test.ts.snap
test/system/cli-entrypoint-create-app.test.ts

tests: system tests based on linked package

---

src/utils/e2e-testing.ts
test/system/cli-entrypoint-create-app.test.ts

Allow custom bin path for `nexus-plugin-prisma`

feat: allow custom bin path for system tests

---

src/lib/backing-types/find.ts
src/lib/backing-types/remap-root-typings.ts
src/lib/layout/index.spec.ts
src/lib/layout/layout.ts
test/__helpers/e2e-system-test.ts
test/e2e/__snapshots__/index.test.ts.snap
test/e2e/index.test.ts
test/system/__snapshots__/cli-entrypoint-create-app.test.ts.snap
test/system/cli-entrypoint-create-app.test.ts

closes #466 and fixes a layout bug

test: add e2e + system test for backing types

---

docs/getting-started/migrate-from-nexus-schema.md

chore(website): fix link to fastify-gql example

---

src/lib/add-to-context-extractor/add-to-context-extractor.ts
src/lib/watcher/runner.ts

Worker threads weren't used anymore at all. This PR fixes that.

fix(context): use worker threads if available

---

src/lib/e2e-testing.ts
test/__helpers/e2e-system-test.ts
test/system/__snapshots__/cli-entrypoint-create-app.test.ts.snap

tests: system test built app

---

docs/getting-started/migrate-from-nexus-schema.md
docs/guides/schema.md
src/cli/commands/create/app.ts
src/runtime/schema/config.ts
test/e2e/__snapshots__/index.test.ts.snap
test/system/__snapshots__/cli-entrypoint-create-app.test.ts.snap

closes #484
- outputs will be nullable by default now

feat(schema): by default nullable outputs

---

docs/api/modules/main/exports/settings.md
src/runtime/server.ts

Document the new setting for `server.path`

docs(settings): settings.server.path

---

src/cli/commands/create/app.ts
src/lib/build/artifact-generation.ts
src/lib/build/build.ts
src/lib/build/deploy-target.ts
src/lib/layout/index.spec.ts
src/lib/layout/layout.ts
src/lib/plugin/index.ts
src/lib/project-root.ts
src/lib/tsc.ts
src/runtime/start.ts
test/__helpers/utils.ts

Simplify system and move toward a cli flag for custom.

feat: cwd-based project root

---

docs/_sidebar.md
src/lib/build/artifact-generation.ts
src/runtime/start.ts

Will do tests another time. Trying to move fast. Use-case came up for this in #534. Typegen generation failing would not cause build failure. And pretty-printing the error was another problem.

feat: crash on unhandled errors

---

docs/_coverpage.md

chore(website): fix casing of GitHub

---

src/cli/commands/create/app.ts
test/__helpers/e2e-system-test.ts

fix: don't install prisma2 cli on init

---

docs/guides/testing.md

chore(website): fix typo

---

package.json
scripts/postinstall.js

improve: postinstall transition notice

---

test/__helpers/e2e-system-test.ts

- https://github.com/graphql-nexus/nexus/runs/561365057
- https://github.com/WordPress/gutenberg/issues/9474
- https://stackoverflow.com/questions/49656445/npm-i-running-command-failed-exit-code-254
yarn works...

tests: fix by avoiding npm

---

package.json
src/runtime/start/start-module.ts
test/__helpers/e2e-system-test.ts
test/system/__snapshots__/system.test.ts.snap
yarn.lock

Regression. Added tests to not regress anymore.
closes #593, #598

fix(build): wrong entrypoint path import and type-fest missing

---

docs/api/modules/main/exports/settings.md
docs/guides/schema.md
src/runtime/schema/index.spec.ts
src/runtime/schema/settings.ts

feat(schema): allow global nullable config

---

src/cli/commands/create/app.ts

fix(init): scaffold prisma entrypoint on init

---

src/lib/e2e-testing.ts
test/__helpers/e2e/create-prisma-app.ts
test/e2e/__snapshots__/create-prisma-app.test.ts.snap
test/system/__snapshots__/create-prisma-app.test.ts.snap

Take advantage of stale sort seeded data.
See https://github.com/graphql-nexus/nexus-plugin-prisma/pull/97.

chore: refactor prisma test

---

docs/guides/conventions.md
src/lib/layout/index.spec.ts
src/lib/layout/layout.ts

feat(layout): just app for entrypoint

---

src/runtime/app.ts
src/runtime/start/dev-runner.ts
src/runtime/testing.ts

On settings gathering pass, do not touch server started state.

fix(server): server start counted only if enabled

---

docs/getting-started/tutorial.md

chore(website): fix tutorial psl add moon

---

docs/getting-started/tutorial.md

This PR in reference to: https://github.com/graphql-nexus/nexus/issues/609
closes #...

Make the steps to deploy to Heroku more clear

---

src/lib/add-to-context-extractor/add-to-context-extractor.ts
src/lib/add-to-context-extractor/extractor.spec.ts
src/lib/add-to-context-extractor/extractor.ts
src/lib/add-to-context-extractor/worker.ts
src/lib/build/build.ts
src/lib/plugin/types/lens.ts
src/runtime/schema/schema.ts
src/runtime/server.ts

Relates to https://github.com/graphql-nexus/nexus/discussions/655#discussioncomment-4613
closes #656

feat(schema): accept async data from addToContext

---

docs/guides/project-layout.md

chore(website): update project-layout.md

---

docs/getting-started/migrate-from-nexus-schema.md

Fix wording regarding versioning.

chore(website): update migrate-from-nexus-schema.md

---

docs/guides/project-layout.md
src/cli/commands/build.ts
src/cli/commands/create/app.ts
src/cli/commands/dev.ts
src/lib/build/build.ts
src/lib/layout/index.spec.ts
src/lib/layout/layout.ts
src/lib/process/index.ts

feat(cli): add --entrypoint flag to dev and build

---

src/lib/build/artifact-generation.ts
src/lib/build/build.ts
src/lib/plugin/utils.ts
src/runtime/start/dev-runner.ts
src/runtime/start/start-module.ts

feat(build): support modern TS module options

---

src/cli/commands/dev.ts
src/lib/build/artifact-generation.ts
src/lib/watcher/index.spec.ts
src/lib/watcher/runner.ts
src/runtime/start/dev-runner.ts

fix(dev-mode): pick up tsconfig compiler options

---

src/cli/commands/create/app.ts

fix(cli): sigterm properly stops init execution

---

docs/_sidebar.md

https://github.com/Camji55/nexus-plugin-jwt-auth

chore(website): added nexus-plugin-jwt-auth to sidebar

---

docs/_sidebar.md

Add `nexus-plugin-shield`, a plugin to use `graphql-shield` with nexus
https://github.com/lvauvillier/nexus-plugin-shield

chore(website): add nexus-plugin-shield to sidebar

---

src/cli/commands/create/app.ts

This PR adds some comments explaning what the `app.ts` file is all about. It also provides some un-commentable examples.
Result:

improve(create-app): annotate entrypoint with comments

---

src/lib/nexus-schema-stateful/typegen.ts

Prevent imports from having duplicates. Related to https://github.com/graphql-nexus/nexus-plugin-prisma/pull/112
This is a workaround. The typegen system needs a proper refactor in order to support Nexus use-cases

fix: prevent duplicate typegen imports

---

src/cli/commands/dev.ts
src/lib/watcher/runner.ts
src/lib/watcher/watcher.ts
src/runtime/dev-mode.ts
src/runtime/server/server.ts

Relates to https://github.com/graphql-nexus/nexus/issues/648#issuecomment-623787514

feat(dev-mode): add --reflection flag

---

docs/index.html

The docs are evolving and have a lot of great stuff spread about, often hard to find. Added search.

chore(website): add docsify search plugin

---

src/lib/watcher/chokidar.ts

Follow-up to in-call discussion about the `nexus-prisma-plugin` hack with the buffered changes when the watcher is paused.
This is not necessary at all anymore, since we don't internally pause the watcher + wait for the server to be listening before resuming the watcher.
Everytime a change is detected the watcher always restarts anyway, so we can just remove all that mess.
Before:
1. file change
2. pause watcher
3. restart runner
4. wait for server to be listening
5. resume watcher
6. execute buffered changes between step 2 and step 5 (if any)
7. file change...
Now:
1. file change
2. restart runner
3. file change...
This will remove the need for https://github.com/graphql-nexus/nexus-plugin-prisma/blob/e7f157e4e15a12b578aeba1c045300bb3867d9c9/src/worktime.ts#L216-L218

improve: remove no longer neccesary watcher debounce

---

src/lib/tsc.ts

closes #796
This PR brings proper errors even when in reflection. It also uses the same `TSError` as `ts-node` to get a closer rendering as `ts-node` which people are used to
The noise is because of `serialize-error` which makes the properties enumerable when deserializing the error. I created an issue about it here: https://github.com/sindresorhus/serialize-error/issues/29

fix: better ts transpilation errors

---

src/cli/commands/dev.ts
src/lib/build/build.ts
src/lib/plugin/utils.ts
src/lib/reflection/fork-script.ts
src/lib/reflection/reflect.ts
src/lib/reflection/stage.ts

fix(plugins): do not serialize during reflection

---

package.json

chore(cmd): fix dev command

---

docs/api/modules/main/exports/schema.md
src/lib/nexus-schema-stateful/stateful-nexus-schema.ts
src/runtime/server/parse-body.ts

closes #647, #670
- add `schema.importType`

feat(schema): add importType method

---

package.json
yarn.lock

improve: tree-shakable @nexus/schema

---

package.json
src/lib/nexus-schema-stateful/stateful-nexus-schema.ts
src/runtime/app.ts
src/runtime/schema/schema.ts
yarn.lock

Fixes type errors happening on build since https://github.com/graphql-nexus/nexus/commit/dfe55b376b258ed642d751ccbd7840bed81850e7.

improve(deps): pin typescript to patch ver for greater stability

---

src/lib/layout/index.spec.ts
src/lib/utils/index.ts
src/runtime/app.spec.ts
src/runtime/server/server.ts
src/runtime/utils.ts

closes #886 
Follow up on #894 which didn't fix all cases of #886

fix(server): req handlers should be noops under reflection

---

docs/api/modules/main/exports/settings.md

chore(website): fix example in settings.md

---

docs/getting-started/migrate-from-nexus-schema.md

See discussion in #942.
Closes #942.

chore(docs): clarify migration paths for nexus schema users

---

docs/guides/testing.md

nanoid it would seem is a named export

chore(docs): nanoid as named export in testing.md

---

docs/tutorial/chapter-2-writing-your-first-schema.md

t.int("body") ==> t.string("body")

chore(website): fix typo in tutorial

---

docs/tutorial/chapter-3-adding-mutations-to-your-api.md

fix schema.extendType parameter error

chore(docs): fix typo in tutorial

---

docs/architecture.md
package.json
src/lib/layout/index.spec.ts
src/lib/layout/layout.ts
src/lib/layout/tsconfig.ts
test/__helpers/e2e/create-prisma-app.ts
website/content/05-meta/04-architecture.mdx

Also fixes system tests with a long delay before attempting query.

fix: temp skip lib check to avoid prisma beta 8 issue

---

src/lib/layout/index.spec.ts
src/lib/layout/tsconfig.ts

feat(tsconfig): lint for correct types and typeRoots

---

src/lib/layout/index.spec.ts
src/lib/layout/tsconfig.ts

feat(tsconfig): enforce noEmit: true

---

src/lib/layout/index.spec.ts
src/lib/layout/layout.ts
src/lib/layout/tsconfig.ts

feat(tsconfig): support extends

---

website/gatsby-node.js

fix: index pages path problem

---

src/runtime/schema/settings.spec.ts
src/runtime/schema/settings.ts

fix: apply auth settings + improve default error formatter

---

src/runtime/schema/settings.ts

fix: allow disabling sdl generation

---

docs/guides/schema.md
website/content/02-guides/02-schema.mdx

chore(docs): fix wrong query example

---

.github/workflows/pr.yml
.github/workflows/trunk.yml
src/lib/fs.ts
src/lib/glocal/detect-exec-layout.spec.ts
src/lib/glocal/detect-exec-layout.ts

fix: glocal check stops at windows disk root

---

.github/workflows/pr.yml
src/lib/fs.ts
src/lib/plugin/manifest.ts
src/lib/utils/index.ts
src/runtime/start/index.spec.ts
src/runtime/start/resolve-from.ts
src/runtime/start/start-module.ts

fix: start module on windows

---

docs/tutorial/chapter-6-testing-with-prisma.md
website/content/01-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx

closes #1112 
This PR will add a message about installing necessary npm packages to the [Setting up the environment ](https://www.nexusjs.org/#/tutorial/chapter-6-testing-with-prisma?id=setting-up-the-environment) section from the chapter 6 of the turorial.

chore(docs): pg & nanoid dep install in tutorial

---

package.json
src/lib/nexus-schema-stateful/stateful-nexus-schema.ts
website/content/04-api/01-nexus/01-schema.mdx
website/content/06-components-standalone/01-schema/01-api/10-api-queryField.mdx
yarn.lock

feat(schema): add subscriptionType

---

src/cli/commands/dev.ts
src/lib/reflection/fork-script.ts
src/lib/reflection/reflect.ts
src/lib/reflection/typegen.ts

fix: print ts related errors happening in reflection

---

website/content/01-getting-started/03-tutorial/03-chapter-2-writing-your-first-schema.mdx

Fix: Change body type from `int` to `string`

chore(website): fix tutorial ch 2 codeblock

---

src/runtime/app.ts
src/runtime/server/server.ts
src/runtime/server/settings.ts
website/content/040-api/01-nexus/04-settings.mdx

feat: add cors support for express

---

website/content/010-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx

chore(docs): fix testing-with-prisma diff in tutorial

---

website/content/010-getting-started/03-tutorial/01-chapter-0-introduction.mdx

chore(docs): add next button to Introduction in tutorial

---

package.json
scripts/postinstall-deps-check.js
src/lib/build/bundle.spec.ts
src/lib/build/bundle.ts
src/lib/build/bundler-fixture/dist/index.js
src/lib/build/bundler-fixture/node_modules/lib-a/dist/index.js
src/lib/build/bundler-fixture/node_modules/lib-a/node_modules/lib-b/package.json
src/lib/build/bundler-fixture/node_modules/lib-a/package.json
src/lib/build/bundler-fixture/package.json
src/lib/tsc.ts
yarn.lock

fix(builder): node_modules weren't walked in some cases

---

website/content/020-guides/120-lifecycle.mdx

chore(docs): fix typo in lifecycle docs

---

src/runtime/server/apollo-server/serverless.ts
website/content/020-guides/09-recipes.mdx

closes https://github.com/graphql-nexus/nexus/issues/1362

fix(serverless): file upload does not work

---

website/content/020-guides/04-logger.mdx

chore(docs): update typo in 04-logger.mdx

---

website/content/030-pluginss/010-prisma/030-runtime.mdx

chore: update docs

---

website/content/010-getting-started/03-tutorial/05-chapter-4-testing-your-api.mdx

chore(docs): minor typo in tutorial

---

src/runtime/server/server.ts
src/runtime/server/settings.ts

fix: subscription typo

---

website/config.js
website/gatsby-config.js

Adds a `robots.txt` file that disallows crawling and listing of all content on this site.

chore: add robots.txt disallowing everything + small stuff
