package.json, src/framework/app.ts, src/lib/logger/__snapshots__/index.spec.ts.snap, src/lib/logger/index.spec.ts, src/lib/logger/index.ts, src/lib/logger/main.ts, src/lib/logger/output.ts, yarn.lock
relates to #204
To keep work incremental this PR does not:
- deeply integrate with framework yet
- have pretty mode
While we use `pino` I opted to wrap it so we have great autocomplete. Here's what raw pino would look like for our users:
Also, note the scrollbar!!
Like `pino` a lot but I see it more as an engine for us than the thing we should directly expose.
I did not use `pino.child` functionality yet. The reason is that it does have the concept of additive API for context. It only permits passing context to children at child creation time. Our API is more flexible in this regard.
=> feat: logger

src/cli/commands/dev.tsx, src/framework/app.ts, src/lib/logger/__snapshots__/main.spec.ts.snap, src/lib/logger/main.spec.ts, src/lib/logger/prettifier.ts, src/utils/logger.ts
- tweak symbols and their coloring for path separation
- tweak key-value symbol separator
- tweak key-value key color
- tweak some of the internal logger names and hierarchy
example, before, without dimmed keys:
=> improve: log pretty rendering

src/framework/app.ts, src/framework/nexus.ts
Note: Regardless of what we decide in #272, `extendType` will still be needed to extend other object types
=> feat: expose missing pieces of nexus surface api

src/cli/commands/create/app.ts, src/cli/commands/create/plugin.ts, src/framework/plugin.ts, tsconfig.json
closes #171
I think the issue is that `esModuleInterop` TS compiler setting forces consumers to
be as well. And that is not good, since its an ugly detail to interop
with legacy non-es-modules. We do not want santa to be cause for user to
have to turn that compiler option on.
=> fix: use explicit default from prompts

docs/references/api.md, src/lib/logger/index.spec.ts, src/lib/logger/root-logger.ts
before:
``` 
rootLogger.setLevel(...)
rootLogger.getLevel() // ... 
rootLogger.setPretty(...)
rootLogger.isPretty() // ...
```
after:
```
rootLogger.sttings({ ... })
rootLogger.settings.pretty 
rootLogger.settings.level
rootLogger.settings.output
```
---
closes #329
=> feat(logger): settings namespace

src/core/plugin/index.ts, src/framework/testing.ts, src/lib/utils/index.ts
This change provides a test context type for internal use that is not
extensible by plugins. Without this a user's app that has plugins that
extend test context will fail to copmile (unless skip lib check is on).
=> fix(testing): TestContextCore for internal

docs/getting-started/tutorial.md, docs/references/api.md, src/cli/commands/create/app.ts, src/framework/app.ts, test/integration/build.spec.ts, test/integration/prisma/build.spec.ts
- supports the mental model
- gives room for the root api surface to grow comfortably
- autocomplete becomes a lot more useful to discover the api
- to address the "but this increases typing" personally still believe in a the global mode concept. I foresee power users opting into "global schema mode" where schema functions are made accessible from anywhere
- we can put js doc annotation on schema prop linking with docs entrypoint for schema
- logical place to add more schema functions. for example the upcoming [`.settings` feature](https://github.com/graphql-nexus/nexus-future/issues/117#issuecomment-580481021)
- all schema related properties and functions are now found under
`app.schema`. Previously they were directly on `app`.
=> feat: app.schema namespace

docs/README.md, docs/getting-started/tutorial.md, docs/guides/logging.md, docs/references/api.md, src/cli/commands/create/app.ts, src/framework/app.ts, src/framework/index.ts, src/framework/start.ts, src/framework/testing.ts, test/integration/build.spec.ts, test/integration/prisma/build.spec.ts
closes #361
- Users no longer can access `app` as named import. Its properties are now themselves named exports.
=> feat(core): app props as named exports

docs/guides/configuration.md, docs/references/api.md, src/framework/app.ts, src/framework/index.ts, src/framework/schema/index.ts, src/framework/schema/schema.ts, src/framework/server.ts, src/framework/testing.ts, src/index.ts, src/lib/logger/index.ts
closes #297
- Settings that used to be passed to `server.start` are now under `server` key in settings input.
- `log.settings` no longer exists. Settings that used to be passed to it are now under `logger` key in settings input.
- `schema.settings` no longer exists. Settings that used to be passed to it are now under `schema` key in settings input.
=> feat(settings): add new system component

src/framework/app.ts, src/framework/schema/config.ts, src/framework/schema/index.ts, src/framework/schema/nexus.ts, src/framework/schema/schema.ts, src/framework/server.ts
closes #368, #369
- Add a `server.custom` api to provide custom server
- This API can also be used to access the underlying express instance
Usage examples:
**Using fastify**
```js
import { settings, server } from 'nexus-future'
import Fastify from 'fastify'
import GQL from 'fastify-gql'
server.custom(e => {
const app = Fastify()
return {
async start() {
app.register(GQL, {
schema: e.schema,
context: req => e.createContext(req)
ide: 'graphiql',
})
await app.listen(e.settings.port)
console.log(
`Server listening at http://localhost:${e.settings.port}/graphiql`
)
},
stop() {
return app.close()
},
}
})
```
**Accessing the default express instance to do some stuff**
```js
server.custom((e) => {
e.defaultServer.instance.use(/*some custom middleware*/)
return e.defaultServer
})
```
=> feat: add server.custom api

docs/getting-started/tutorial.md
I suggest to remove the mention of Prisma here as Nexus newcomers at this point shouldn't care that Prisma is used (the extreme case is that they don't even know what Prisma is, so including it might be confusing).
=> docs: more accessible initial tutorial aside

src/framework/schema/config.ts, src/lib/add-to-context-extractor/add-to-context-extractor.ts, src/lib/add-to-context-extractor/worker.js, src/lib/build/build.ts, src/utils/fs.ts
This refactor removes the last place where addToContext type extraction
was integrated outside the new lib module. There was a wacky environment
variable system in use for passing the data at build time from build
module to nexus schema config module. Now the system used at build is
the same one used in dev!
=> refactor: add-to-context typegen on build

docs/api.md, src/framework/app.ts, src/framework/schema/config.ts, src/framework/schema/index.ts, src/framework/schema/nexus.ts, src/framework/schema/schema.ts, src/lib/layout/layout.ts
closes #427
closes #448
This PR replaces #448 by @mohe2015 (thanks @mohe2015!). This is because:
1. We want to ship the initial version as a new opt-in schema setting
2. This part of the codebase is really a terrible mess and was hard
enough for me to navigate let alone guide an external contributor
through it.
Why opt-in?
- Because its not obvious that generating this file all the time is the
best default.
- We can add a default soon
- In a backwards compatible way (pre 1.0 so not a big deal though)
Why explicit path?
- Because its not obvious that `generated/schema.graphql` is the best
default. For example `api.grpahql` in project root?
- We can add a default soon
- In a backwards compatible way (pre 1.0 so not a big deal though)
Other points
- I thought about enabling by default into …
=> feat(schema): graphql sdl generate setting

docs/getting-started/migrate-from-nexus-schema.md
Fix typo `generaate` -> `generate` on bottom of [Document - Migrate](https://www.nexusjs.org/#/getting-started/migrate-from-nexus-schema?id=prisma)
=> chore: fix docs typo generate

src/framework/schema/config.ts, src/framework/schema/schema.ts, src/lib/add-to-context-extractor/add-to-context-extractor.ts, src/lib/build/build.ts, src/lib/layout/layout.ts, src/lib/watcher/runner.ts, src/utils/artifact-generation.ts, src/utils/tsc.ts
- Make sure build errors are caught and make the command fail
- Do not generate the schema file in "prod"
- Delete the TS incremental file when running `build` to always start from a clean slate
- Refactor `createTSProgram`
=> fix(build): use layout only in dev

src/cli/commands/dev.ts, src/lib/layout/index.ts, src/lib/layout/layout.ts, src/lib/plugin/index.ts, src/lib/watcher/chokidar.ts, src/lib/watcher/link.ts, src/lib/watcher/runner.ts, src/lib/watcher/types.ts, src/lib/watcher/watcher.ts
closes #91
Alt name:
```
feat: onBeforeWatcherStartOrRestart hook
```
- allow async work before watcher start
- allow async work before watcher restart
- allow worker to impact runner (so far: env)
- allow worker to know if restart is due to plugin
Before:
After:
After with e.g. add file:
=> feat: onBeforeWatcherStartOrRestart hook

src/cli/commands/create/app.ts
Looks like an update of prettier made it fail when a pattern doesn't match any file.
This PR makes prettier run only after the plugins have run their base setup, which makes sense anyway.
=> fix: run typegen after plugin base setup

src/lib/nexus-schema-stateful/stateful-nexus-schema.ts, src/runtime/schema/schema.ts
Stateful nexus schema is better focused now. It doesn't need to control the make schema part. Just the accumulation of types.
=> refactor(schema): reduce indirection

.github/workflows/trunk.yml, .gitignore, components/schema.d.ts, components/schema.js, package.json, plugin.d.ts, plugin.js, scripts/build-module-facades.js, testing.d.ts, testing.js
This cleans up the package facade system. It is easier to manage now because the pattern in use is centrally readable and changeable. We also remove noise from the project, as the facades aren't meaningful for our development, and so shouldn't be visible in our day to day work.
Cleaning before dev is also good. It removes the possibility of stale buildinfo making tsc incremental build act weird (which I've had happen to myself multiple times a week).
=> refactor: build module facades on the fly

docs/guides/testing.md, src/runtime/testing.ts
Extending the testing context interface type must now be done using name
`NexusTestContextApp` instead of `nexusFutureTestContextApp`.
We need to update Prisma plugin.
=> feat: remove future term from global interface

docs/_sidebar.md, docs/guides/debugging.md, src/cli/commands/create/app.ts, src/cli/commands/dev.ts, src/lib/watcher/link.ts, src/lib/watcher/types.ts, src/lib/watcher/watcher.ts
Fixes a regression. `--inspect-brk` is passed to `fork` again in the watcher
=> fix: vscode debugging

src/lib/build/deploy-target.ts
Unfortunately, I was unable to get a proper now deployment with the suggested @now/node-server build, it always broke.
After some fiddling around, and as a workaround until the now-nexus builder in working, I worked out that patching the build command worked.
In my `now.json`:
```json
{
"builds": [{ "src": "dist/index.js", "use": "@now/node" }],
"routes": [{ "src": "/.*", "dest": "dist/index.js" }]
}
```
And I also found out that the `@now/node-server` builder has been deprecated in favour of the `@now/node` builder.
=> fix: enforce @now/node builder

docs/api/modules/main/exports/schema.md, docs/index.html, src/lib/watcher/index.spec.ts, src/runtime/app.ts, src/runtime/schema/index.spec.ts, src/runtime/schema/schema.ts
=> feat(schema): add schema.middleware

docs/_coverpage.md, docs/getting-started/migrate-from-nexus-schema.md, docs/getting-started/tutorial.md, docs/guides/cli.md, docs/guides/writing-plugins.md, docs/references/recipes.md, src/cli/commands/create/plugin.ts
Mostly about docs but we also change the plugin scaffolding template.
=> improve: drop next dist tag

docs/components/schema/plugins/prisma.md
=> chore(website): update prisma.md

docs/api/modules/main/exports/settings.md, package.json, src/lib/plugin/types/lens.ts, src/lib/utils/index.ts, src/runtime/app.ts, src/runtime/schema/settings.ts, src/runtime/server/index.ts, src/runtime/server/logger.ts, src/runtime/server/server.ts, src/runtime/server/settings.ts, src/runtime/start/dev-runner.ts, yarn.lock
closes #683 
Went on a server settings refactor to better support more config in the future. It also streamlines how settings is managed in other components
=> feat(server): add playground.path configuration

package.json, src/lib/plugin/types/lens.ts, src/lib/utils/index.ts, src/runtime/server/settings.ts, yarn.lock
Because `utility-types` is used on the plugin interface (and thus the public api), it cannot be a dev dependencies.
Given that we only use two of its type, I decided to remove it so that it doesn't end up in the `dependencies`. I copy & pasted the two types instead (`DeepRequired` & `DeepPartial`)
=> fix: build error because of utility-types

src/lib/build/build.ts, src/lib/build/deploy-target.ts, src/lib/layout/index.spec.ts, src/lib/layout/layout.ts, src/lib/layout/tsconfig.ts, src/lib/tsc.ts, src/runtime/start/start-module.ts
- closes #685, 
- Refactor layout to normalize build output as absolute path
- Fix precedence of build output. User input > outDir > default
- Make ts use the right build output
- Fix heroku/now deployment validation
- Add tests
=> fix: custom build output (`nexus build -o`)

docs/getting-started/tutorial.md
closes #706 
Just a small fix in the getting started tutorial. There was a name mismatch between a column in the DB schema and the GraphQL schema.
Side note: really excited about the deep focus on user experience by nexusjs.
cc @jasonkuhrt
- ~~[ ] docs~~
- ~~[ ] tests~~
=> chore(website): fix mismatch between db/gql schemas in tutorial

docs/plugins/prisma.md
The roles are defined as
```ts
enumType({
name: 'Role',
members: ['MEMBER', 'EDITOR'],
})
```
but the "output" is 
```gql
enum Role {
AUTHOR
EDITOR
}
```
This fixes the wrong output role
=> chore(website): fix enum example mismatch

src/lib/add-to-context-extractor/extractor.spec.ts, src/lib/add-to-context-extractor/extractor.ts
Add missing union type extraction when generating context types.
relates #440
=> feat(schema): extract union type refs in addToContext

docs/api/modules/main/exports/server.md, docs/architecture.md, src/lib/reflection/fork-script.ts, src/lib/reflection/stage.ts, src/runtime/app.ts, src/runtime/schema/index.spec.ts, src/runtime/schema/index.ts, src/runtime/schema/schema.ts, src/runtime/schema/settings.ts, src/runtime/server/handle.ts, src/runtime/server/request-handler-playground.ts, src/runtime/server/server-old.ts, src/runtime/server/server.ts, src/runtime/server/settings.ts, src/runtime/settings/index.ts, src/runtime/start/dev-runner.ts, src/runtime/start/start-module.ts, src/runtime/testing.ts
Motivations:
- decouple concept of starting server from assembly to support future serverless feature #782 
- assembly is the process of gathering the lazy state into a final runnable one 
- settings is now a component like schema and server
- the components are designed to look a lot more symmetrical now
- root app state is passed down to components which attach their namespaced state to, easier to reason about, think redux
- introduce concept of checks that runs after schema assembly
- `server.start` and `server.stop` are no longer exposed. If you had a use-case for them please open an issue to discuss.
=> feat: app assembly

docs/README.md
Removed a trailing `]` character from one of the readme links.
=> chore(website): Remove extra ] from link url

docs/guides/project-layout.md, src/lib/build/build.ts, src/lib/layout/tsconfig.ts, src/lib/tsc.ts
closes #702, related to https://github.com/graphql-nexus/nexus/issues/648#issuecomment-623788375
=> feat(tsconfig): support noEmit: true

docs/api/modules/testing.md, src/runtime/schema/settings.ts, src/runtime/server/server.ts, src/runtime/server/settings.ts, src/runtime/testing.ts
closes #803 
This PR will be merged as rebase. It does a couple of things:
- Fixes server settings that were no longer working (regression)
- Fixes `app.stop()` which was always warning that the server wasn't run because `running` was never set to true (regression)
- Fixes #803 where the app singleton wasn't properly required (regression)
- Add an option to specify a custom entrypoint if one is needed and used with `nexus dev | build`
- Makes sure that if the user app calls `settings.change({ server: { ... } })`, the test context server settings are still applied
=> fix + enhance: test context

src/lib/package-manager.ts
Lockfiles are not colocated with the root directory in monorepos, or just nonexistent. Use `process.env.npm_config_user_agent` before looking for a lockfile. Tested from CLI.
closes #824
=> fix: check process useragent first to detect package manager

.gitignore, package.json, tsconfig.cjs.json, tsconfig.esm.json, tsconfig.json
closes #829
This does not make the sub-modules esm compatible. Maybe there is a way to make other package dirs have esm builds, but so far not aware. We'll see how this goes. Most use-cases should be for the default (main) dir.
=> feat: publish esm builds

package.json, src/lib/utils/index.ts, yarn.lock
closes #167
While this may not seem like an improvement for end-users, but rather an internal refactor, the user-facing part is in how it helps support #119. It turned out that codename uses some dynamic requires that rollup commonjs plugin cannot understand.
=> improve: remove codename dep

docs/api/modules/main.md, docs/api/modules/testing.md, docs/guides/testing.md, docs/references/recipes.md, src/runtime/testing.ts
closes #857 
This aligns with changes to the server component api where `start`/`stop` are no longer methods. This is because the concept no longer made sense in a serverless context.
Before:
```ts
let ctx
beforeAll(async () => {
Object.assign(ctx, await createTestContext())
await ctx.app.server.start()
})
afterAll(async () => {
await ctx.app.server.stop()
})
```
After:
```ts
let ctx
beforeAll(async () => {
Object.assign(ctx, await createTestContext())
await ctx.app.start()
})
afterAll(async () => {
await ctx.app.stop()
})
```
=> feat(testing): relocate server start/stop to app

docs/components/logger/api.md
Removed hardcoded hostname from the absolute url.
closes #...
=> chore(docs): fix link

src/lib/plugin/index.spec.ts, src/lib/plugin/load.ts, src/lib/plugin/plugin.fixture.js, src/lib/plugin/types/lens.ts, src/lib/utils/index.ts, src/runtime/testing.ts
This PR fixes too permissive typings that were used to type the plugin testtime contributions and guards against contribution that would not be objects.
It's related to https://github.com/graphql-nexus/nexus-plugin-prisma/pull/125
=> fix: testtime contribution typings

src/lib/plugin/types/lens.ts, src/testing.ts, src/testing/index.ts, src/testing/testing.ts
The Nexus testing component may depend on worktime deps, it is not bound by the goal for minimalism that runtime is. Having it within runtime is thus confusing.
closes #...
=> refactor: group testing logic under own dir

docs/README.md, docs/guides/project-layout.md, scripts/build-module-facades.js, src/lib/layout/index.spec.ts, src/lib/layout/tsconfig.ts, src/typescript-language-service/index.ts
This change introduces a TypeScript Langauge Service.
It needs to be used in the tsconfig like so:
```js
{
"compilerOptions": {
"plugins": [{ "name": "nexus/typescript-language-service" }]
},
}
```
Nexus will automate management of this config, ensuring:
1. If present, that it is correctly configured
2. If not present, added
Before / After this change:
- Server
- Settings
- log
closes #...
=> feat(tslsp): exclude autocompletions from private api

docs/_sidebar.md, docs/api/modules/main/exports/logger.md, docs/api/modules/main/exports/schema.md, docs/api/modules/main/exports/server.md, docs/api/modules/main/exports/use.md, docs/components/schema/api/_sidebar.md, docs/guides/logger.md, docs/guides/plugins.md, docs/guides/schema.md, docs/guides/server.md, package.json, src/runtime/app.ts, src/runtime/index.ts, typescript-language-service/index.d.ts, typescript-language-service/index.js
- New nxs.li links have been created for:
- component api docs
- component guides
- component issues
- These have been used in the website docs and in jsDoc
- jsDoc is added for the following:
- all named exports
- app default export
- all components of `app` (copy of what is on named exports)
- It is intentional that the jsDoc only contains links right now now. We should figure out if we can add a simple string replace build step to inline content that is shared between website and jsDoc, and between jsDoc nodes.
- A logger guide section is started based on existing content in the api doc that was heavy on discussion.
- There is no guide content for settings yet so no link for that.
- Examples:
=> docs: jsdoc links to website in runtime exports

docs/references/recipes.md
=> chore(website): fix type in recipes.md

docs/guides/project-layout.md
=> chore(website): fix typo in project-layout.md

src/lib/build/build.ts, src/lib/build/bundle.spec.ts, src/lib/build/deploy-target.ts, src/lib/layout/layout.ts, src/lib/utils/index.ts
closes #919
This change also does some slight refactoring by keeping more information in layout.
This change also improves the Heroku start module check in two ways.
First by being more flexible about what is tolerated in the start script. For example it is not possible to pass flags to node in the start script.
Second, some colouring to make more clear to the user what is wrong and what a fix looks like.
=> fix(build): heroku/vercel deploy targets

src/cli/commands/create/app.ts, src/cli/commands/dev.ts, src/cli/commands/report.ts, src/lib/build/build.ts, src/lib/glocal/utils.ts, src/lib/layout/index.spec.ts, src/lib/layout/layout.ts, src/lib/report.ts, src/testing/testing.ts
This refactor just changes the return type of layout, and then handles the
cascading updates needed.
This small step puts us in a position to more easily refactor all the
fatals within/under the layout moudle, of which there are many.
=> refactor(layout): return either type

docs/references/recipes.md
Addresses typo mentioned in #640.
Ran with clean `npx nexus`. Not sure if this changed recently. FWIW `rootDir` changes nothing without `outDir` being specified. People may be compiling things outside of `api`, obviously, but if nexus specifies the root and `includes` in the generator it'd be a little cleaner to get rid of the extra nested dir. By that I mean relocate `api/*` to `.nexus/build` to keep the structure a little more obvious.
=> chore(docs): fix directory in example start script

docs/tutorial/chapter-1-setup-and-first-query.md
`schema` was misspelled as `scheam`
=> chore(website): fix typo in tutorial

docs/api/modules/main/exports/settings.md, src/runtime/schema/settings-mapper.ts, src/runtime/schema/settings.spec.ts, src/runtime/schema/settings.ts
Enable the authorization plugin by default. Can be disabled via the settings.
=> feat: add authorization plugin by default

docs/guides/project-layout.md, src/cli/commands/create/app.ts, src/lib/build/build.ts, src/lib/build/deploy-target.ts, src/lib/layout/build.ts, src/lib/layout/cache.ts, src/lib/layout/index.spec.ts, src/lib/layout/index.ts, src/lib/layout/layout.ts, src/lib/layout/schema-modules.ts, src/lib/layout/tsconfig.ts, src/lib/package-json.ts, src/runtime/schema/schema.ts, website/content/02-guides/06-project-layout.mdx
=> feat: treat fist package.json as project root

package.json, src/lib/layout/index.spec.ts, src/runtime/__snapshots__/app.spec.ts.snap, src/runtime/app.spec.ts
This forces color in tests.
Typically in our terminals chalk will detect the TTY and use color. But in CI the opposite happens. That breaks snapshots. But snapshotting terminal output with color has the benefit of making sure we're doing color right, which is important for DX.
I'm not sure how Windows will react to this but I'm hopeful that GH Actions windows os uses [Windows Terminal](https://github.com/chalk/chalk#windows). If not we might have to disable color or disable just for windows.
=> chore: force color always in tests

docs/api/modules/main/exports/server.md, src/lib/utils/index.ts, src/runtime/app.spec.ts, src/runtime/server/server.ts, website/content/04-api/01-nexus/03-server.mdx
This exposes the underlying Node HTTP Server instance. It is placed under `raw` to make clear that it is not for normal day to day use.
This feature was motivated to support things like #278 
While we wish, as a framework, this didn't have to exist, we don't want to be a bottleneck for the community to experiment and collaborate. Thus escape hatches like this.
closes #840
=> feat(server): expose node http server instance

docs/guides/project-layout.md, src/lib/layout/index.spec.ts, src/lib/layout/tsconfig.ts, website/content/02-guides/06-project-layout.mdx
closes #1036
This adds support for `typeRoots`. It introduces the following logic:
- tsconfig MUST have `compilerOptions.typeRoots` set
- tsconfig `compilerOptions.typeRoots` MUST include `"types"`
- tsconfig `compilerOptions.typeRoots` MUST include `"node_modules/@types"`
- tsconfig `compilerOptions.typeRoots` MAY include other values
The product design here is really a cascade of effects:
- want to avoid users having to configure typegen paths
- use ts default of @types
- users can break this
- prevent users from breaking it by removing supprt for typeRoots
- users need typeRoots for custom local package typings
- ok fine, support typeRoots but force the @types value
- and finally, while we're at it, introduce a convention becuase Nexus
can help users (zero-config) a bit by doing so. …
=> feat(tsconfig): support type-roots

src/lib/add-to-context-extractor/extractor.spec.ts, src/lib/add-to-context-extractor/extractor.ts, src/lib/add-to-context-extractor/typegen.ts
closes #1032
This makes the context extractor able to understand when the return type is a reference.
```ts
export type Foobar = { /* ... */ }
schema.addToContext(() => {
return { /* ... */ } as Foobar
})
```
Previously this would have resulted in bad typegen like:
```ts
interface Context Foobar
```
Now it results in correct type gen like:
```ts
import { Foobar } from '...'
interface Context extends Foobar {}
```
=> feat(context): addToContext can return type refs

src/lib/graphql-client/index.ts
Currently `ctx.client.headers` does not work in `nexus/testing` due to the structural mismatch between `Headers` in`cross-fetch` and `Headers` in`graphql-request`. 
This PR converts `headers` from `cross-fetch` format to a simple plain object, so that `GraphQLClient` from `graphql-request` can consume it.
=> fix(testing): ctx.client sends set headers

src/lib/process/index.ts
The "heuristic" to prevent from clearing is now based on the nexus logger. It will prevent from clearing the console on restarts when either:
- LOG_LEVEL
- LOG_FILTERING
- NEXUS_NO_CLEAR
is present in the env. `NEXUS_NO_CLEAR` is added mostly for internal debugging purpose in case we ever need that ourselves.
=> fix: clear console when using prisma

.github/workflows/pr.yml, .github/workflows/trunk.yml, package.json, src/lib/test-context/fs.ts, src/lib/watcher/index.spec.ts, src/lib/watcher/runner.ts, yarn.lock
Technical notes:
TIL:
- https://superuser.com/questions/176388/why-does-windows-use-backslashes-for-paths-and-unix-forward-slashes/176395#176395 via https://github.com/sindresorhus/slash#slash-
Problem:
We were having weird issues with `\`.
[Specifically](https://github.com/graphql-nexus/nexus/runs/816374829#step:6:4):
```
SyntaxError: Octal escape sequences are not allowed in strict mode
```
coming from this LOC in `watcher/runner.ts`:
```ts
eval(process.env.ENTRYPOINT_SCRIPT)
```
When the string to eval was:
```
require('C:\Users\RUNNER~1\AppData\Local\Temp\37742529471191166\entrypoint')
```
I don't know why this did not fail in linux.
Windows treated this string as if the `\` were not escaped, so for example `\377` was treated as octal escape sequence...
I finally realized that:
1. …
=> test: add watcher to windows suite

.github/workflows/pr.yml, .github/workflows/trunk.yml
This refactor finally consolidates the Windows support we've incrementally added for unit tests. Now we just add windows to the unit test os matrix.
=> chore: refactor windows cicd

src/lib/layout/index.spec.ts, src/lib/layout/layout.ts
New look, we no longer control logging problem and solution as two separate logs, is fine:
=> refactor(layout): return either on no-modules-or-nexus-module

website/content/01-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx, website/content/01-getting-started/03-tutorial/05-chapter-4-testing-your-api.mdx, website/content/01-getting-started/03-tutorial/06-chapter-5-persisting-data-via-prisma.mdx, website/content/01-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx, website/content/01-migration-guides/02-nexus-schema-users.mdx, website/content/02-guides/05-testing.mdx, website/content/02-guides/09-recipes.mdx
Replaced with `json`/`ts` etc - preserves syntax highlighting and +/1 still work.
=> chore(website): Removed unnecessary diff blocks

src/runtime/server/handler-graphql.spec.ts, src/runtime/server/handler-graphql.ts, src/runtime/server/server.ts, src/runtime/server/settings.ts
closes #1168
Graphql instrospection is now disabled by default in production.
A new setting can control this behavior:
```typescript
settings.change({
server: {
graphql: {
introspection: true
}
}
});
```
=> feat(server): disable graphql introspection in production

src/runtime/server/error-formatter.ts, src/runtime/server/handler-graphql.spec.ts, src/runtime/server/handler-graphql.ts, src/runtime/server/server.ts, src/runtime/server/utils.ts
closes #1186, related to #1182
In dev (displaying the message and repeating the stack is based on [a suggestion from Ivan Goncharov here](https://github.com/graphql/graphql-js/issues/2215#issuecomment-540054812)):
In production (structured logs):
=> fix: display stack traces on graphql errors

website/content/05-meta/04-architecture.mdx
Currently the last two bullet points look funny in the layout as they are on the top level, but the text before is intended one level. 
I think the text should be on the top level as well, so I fixed that.
It could be possible that it is meant to be intended - let me know and I will update the PR then.
=> chore(website): Fix indentation of "In conclusion" for dependency info

src/runtime/server/handler-graphql.ts, src/runtime/server/server.ts, src/runtime/server/settings.ts, website/content/040-api/01-nexus/04-settings.mdx
Use the .enabled pattern for playground.
Also fixes some settings bugs under incremental usage. Previously
multiple partial sets of playground settings would result in previous
playground settings getting blown away.
Also changes the settings data representation of cors to be based on nested enabled property.
=> feat(settings): server.playground.enabled

src/lib/add-to-context-extractor/extractor.spec.ts, src/lib/add-to-context-extractor/extractor.ts
closes #1299
The first use-case for this came from manually using Prisma with Nexus, a new example https://github.com/graphql-nexus/examples/pull/66
=> feat(context): extract type imports from generics

website/content/010-getting-started/03-tutorial/05-chapter-4-testing-your-api.mdx, website/content/010-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx, website/content/020-guides/05-testing.mdx
closes #1218
relates to https://github.com/graphql-nexus/nexus/issues/1217#issuecomment-663459021
I surprisingly can't find any issue about the underlying problem. This fixes the testing component, which wasn't able to run tests whenever there was a type error. That would happen fairly often right after installing Jest for instance, which deletes all the generated types. It should also fix the tutorial.
=> chore(website): improve docs around jest testing

website/content/020-guides/02-schema.mdx
Noticed this, not sure if it's a typo or based on an older API.
=> chore(docs): Update schema.enum to schema.enumType in guide

scripts/postinstall-typegen-script.js, scripts/postinstall.js
=> fix: postinstall false negative deps warning

website/content/020-guides/110-configuration-management.mdx
=> website(docs): fix typo

src/runtime/server/apollo-server/serverless.ts, src/runtime/server/server.ts
Updates playground and CORS settings equally as server-mode.
Prevents "▲ nexus:server CORS does not work for serverless handlers. Settings will be ignored." from showing when CORS isn't enabled by user.
=> fix(serverless): Fixes boolean checks for cors

src/testing/testing.ts, website/content/040-api/02-nexus-testing.mdx
Using `createTestContext` in a monorepo setting leads to the `Layout.create` function detecting the top level package.json and error out because that one doesn't have it's own name. However, by exposing the `projectRoot` option already accepted by `Layout.create`, we can circumvent this by resolving the path ahead of time, i.e.:
```ts
Object.assign(ctx, await originalCreateTestContext({ projectRoot: path.join(__dirname, '../..') }))
```
=> improve: expose projectRoot setting in createTestContext

website/content/010-getting-started/03-tutorial/02-chapter-1-setup-and-first-query.mdx
=> chore(docs): fix typo in 02-chapter-1-setup-and-first-query

package.json, src/runtime/server/server.ts, src/runtime/server/settings.ts, yarn.lock
=> feat(server): add a subscriptions server

website/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
=> chore(docs): minor typos in tutorial
